//
//  AppDatabaseImporter+CoreData.swift
//  TempProject
//
//  Created Eugeniy Zaychenko on 11/12/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import PromiseKit
import CoreData

class CoreDataWriter<ImportedType> {}

extension CoreDataWriter: DatabaseWriterProtocol where ImportedType: CoreDataCompatible {
    
    typealias WriteType = ImportedType
    
    static func deleteEntities(_ entity: WriteType.Type, predicate: NSPredicate?) -> Promise<Void> {
        
        return Promise<Void> { seal in
            
            CoreDataStorageController.shared.delete(WriteType.ManagedType.self, with: predicate) {
                seal.fulfill(Void())
            }
        }
    }
    
    static func importRemoteList(_ objectsToImport: [WriteType?]) -> Promise<Void> {
        
        return Promise<Void> { seal in
            
            CoreDataStorageController.shared.insertList(objects: objectsToImport) {
                seal.fulfill(Void())
            }
        }
    }
    
    static func updateRemote(_ objectToImport: WriteType?, predicate: NSPredicate?) -> Promise<Void> {
        
        return Promise<Void> { seal in
            
            CoreDataStorageController.shared.insertAsync(object: objectToImport, predicate: predicate) {
                seal.fulfill(Void())
            }
        }
    }
    
    static func importValues(_ entity: WriteType.Type, predicate: NSPredicate?, values:  [String: Any]) -> Promise<Void>  {
        
        return Promise<Void> { seal in
            
            CoreDataStorageController.shared.setValues(type: entity, values: values, predicate: predicate) {
                seal.fulfill(Void())
            }
        }
    }
}

